[feat] Add commands of math formulas
ostis-ai/tex2scs-translator pull request #24
Opened 2024-07-10 09:01 UTC by MakarenkoAI

2024-07-26 09:23 UTC, MksmOrlov requested changes
update tests/documentation for math please

2024-07-26 09:23 UTC, MksmOrlov commented on src/grammar/SCnTexLexer.cpp
> +// Generated from /home/anna/projects/tex2scs-translator/src/grammar/SCnTex.g4 by ANTLR 4.7.2
absolute path is not a good idea, fix it everywhere in PR

2024-07-29 08:03 UTC, NikitaZotov requested changes

2024-07-29 08:03 UTC, NikitaZotov commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 2.8.12)
```suggestion
cmake_minimum_required(VERSION 3.11)
```

2024-07-29 08:03 UTC, NikitaZotov commented on CMakeLists.txt
> +set(CMAKE_BUILD_TYPE Debug)
```suggestion
```

2024-07-29 08:03 UTC, NikitaZotov commented on README.md
> +With space!
```suggestion
```

2024-07-29 08:03 UTC, NikitaZotov commented on src/translator/commands/math/sc_scn_tex_operation_command.h
> +  uint8_t const D_ATTR_POS = 3;
Please, provide more meaningful names for this values

2024-07-29 08:03 UTC, NikitaZotov commented on src/translator/commands/math/sc_scn_tex_math_command.cpp
> +      auto const openBracketOfFirstArg = [&]() -> std::string {
```suggestion
      auto const OpenBracketOfFirstArg = [&]() -> std::string {
```

2024-07-29 08:03 UTC, NikitaZotov commented on src/translator/commands/math/sc_scn_tex_math_command.cpp
> +        std::string const & first_argument = params.at(FIRST_PARAM_POS);
```suggestion
        std::string const & firstArgument = params.at(FIRST_PARAM_POS);
```

2024-07-29 08:03 UTC, NikitaZotov commented on src/translator/commands/math/sc_scn_tex_math_command.cpp
> +        std::string const & first_argument = params.at(FIRST_PARAM_POS);
Review all your code style. It should be a code style of the main code

2024-07-29 16:03 UTC, MksmOrlov approved these changes

2024-08-01 14:47 UTC, NikitaZotov approved these changes

2024-08-01 15:16 UTC, merged